# Generated by Django 2.2.3 on 2019-07-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcar',
            name='id',
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='idAssignedCar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='control.AssignedCars'),
        ),
    ]
